# gcc8's support for C++17 is still considered experimental, use a
# newer version where available.
c_compiler_version:    # [linux]
- '9'                  # [linux and not aarch64 and not ppc64le]
- '8'                  # [linux and ppc64le]
- '10.2.0'             # [linux and aarch64]
cxx_compiler_version:  # [linux]
- '9'                  # [linux and not aarch64 and not ppc64le]
- '8'                  # [linux and ppc64le]
- '10.2.0'             # [linux and aarch64]
MACOSX_SDK_VERSION:        # [osx and x86_64]
  - 10.15                  # [osx and x86_64]
MACOSX_DEPLOYMENT_TARGET:  # [osx and x86_64]
  - "10.15"                # [osx and x86_64]
CONDA_BUILD_SYSROOT:       # [osx and x86_64]
  - /opt/MacOSX10.15.sdk   # [osx and x86_64]