{% set version = "2022.01.18" %}

package:
  name: crender
  version: {{ version }}

source:
  git_url: https://github.com/anaconda-distribution/crender.git
  git_rev: 7bfb82c65fad2e8121d95c5cca3d2b4d3dd3cc30

build:
  number: 0
  skip: True  [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - git
    - ninja
  host:
    - boost

test:
  commands:
    - crender --help

about:
  home: https://github.com/anaconda-distribution/crender
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'The crender tool for creating and checking conda recipes'
  dev_url: https://github.com/anaconda-distribution/crender

extra:
  recipe-maintainers:
    - tkoch
