{% set version = "0.3" %}

package:
  name: crender
  version: {{ version }}

source:
  git_url: https://github.com/anaconda-distribution/crender.git
  git_rev: 9688dd815a043173eb2591fe1f3b426aa3fe4603
  patches:
    # gcc8: link with -lstdc++fs to overcome std::filesystem issue. For more info, see: https://gitlab.kitware.com/cmake/cmake/-/issues/17834
    - patches/gcc8-fs.patch  # [linux and ppc64le]

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - patch  # [linux and ppc64le]
    - git
    - ninja

about:
  home: https://github.com/anaconda-distribution/crender
  license: MIT
  license_file: LICENSE
  summary: 'The crender tool for creating and checking conda recipes'
  dev_url: https://github.com/anaconda-distribution/crender

extra:
  recipe-maintainers:
    - tkoch
    - sbailey
